### ISSUE TITLE
Как использовать?

### ISSUE THREAD

**Issue by devnes** [BringerPro/russian-post-api-client-php#1]
Есть хоть какое-то описание методов или информации "как начать?"?

**Comment by fearrr** [comment]
@devnes, так это, getF7(), sendF103(), все же понятно, что тут думать, названия методов говорят сами за себя.
Кто не понял, тот поймет.

**Comment by dmamontov** [comment]
@devnes Это стандартный АПИ клиент. что там может быть сложного. Создаете экземпляр класса и обращаетесь к соответствующим методам.
